linters:
  enable-all: true
  disable:
  - structcheck
  - interfacer
  - exhaustivestruct
  - golint
  - scopelint
  - maligned
  - nosnakecase
  - varcheck
  - deadcode
  - ifshort
  - gci
  - rowserrcheck
  - sqlclosecheck
  - structcheck
  - wastedassign
  - gomoddirectives

linters-settings:
  staticcheck:
    go: "1.19"
  stylecheck:
    go: "1.19"
  ireturn:
    allow:
    - anon
    - error
    - empty
    - stdlib
    - netlink

issues:
  exclude:
  - "only one cuddle assignment allowed before if statement"
  - "should be written without leading space as `//nolint"

run:
  timeout: 10m
  skip-files:
  - "zz_generated.*\\.go$"
  - ".*conversion.*\\.go$"
  skip-dirs:
  - third_party
  - api
  allow-parallel-runners: true


# only one cuddle assignment allowed before if statement
